### PR TITLE
Migrate roles.js

### LINKED ISSUE #135: Role Colors migration request
For role colors, those need to be pulled out of the code and imported into the LDSG Management sheet. The expected format of the sheet is going to be:
Role (Numeric string), color role (Numeric string), inherited from role (Numeric string), If the inherited role should be kept if this role is applied (Boolean)

Subject to change as needed.

### PR DESCRIPTION
**Pull request by BobbyTheCatfish**
Resolves #135, and is related to #17, #6, and #16 although no code from that was referenced.

Roles.js has been turned into `/role`
Most of the core functionality has stayed the same, but it now relies on a google sheet. I've attached a screenshot of what the document should look like. The reference name is just for document organization and isn't read by the bot

The type needs to be either `EQUIP` or `ADD`

Screen Shot 2022-08-14 at 1 41 09 AM

Adds node-schedule since there can be local changes on the sheet that need to be updated. If requested, I could create a few subcommands for adding/removing roles from the sheet.

### CODE REVIEW

**Comment by Maldor** [comment]
Just did some initial setup in the sheet, and the formula that is being used errors out as a circular reference in google sheets unless iterative calculations are turned on, I will look to see if there is a better way to do what you are trying to do

**Comment by Maldor** [comment]
Or... I could, you know, look at what cell is selected and program it right...

**Comment by Maldor** [comment]
Although, this might be a better equation to use:
image

**Comment by BobbyTheCatfish** [comment]
That's what I originally had, but the way this code works,
https://github.com/LaughLax/icarus5/blob/d6c5666e2507190d74685dd40961166cfbc6487f/modules/roles.js#L20-L22

It checks the role to see if the parent roles includes one of the user's roles. If it was like this, it would give everything to the lowest role.

**Comment by BobbyTheCatfish** [comment]
Here's an example where I only have the year 1 role, but I have all of the year role colors available
Screen Shot 2022-08-14 at 2 21 13 AM

**Comment by Maldor** [comment]
Ahh ok.
@LaughLax The settings sheet is ready as an example with the equation and layout

**Pull request merged**
